version: "3.8"

services:
  postgres_service:
    image: postgres:14
    container_name: postgres-sandbox
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb01
    ports:
      - "5432:5432"
    volumes:
      - postgres-sandbox:/var/lib/postgresql/data
      # - ./migrations:/docker-entrypoint-initdb.d

  pgadmin_service:
    image: dpage/pgadmin4:6.11
    container_name: pgadmin-sandbox
    ports:
      - 8080:80
    volumes:
      - pgadmin-sandbox:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - postgres_service

volumes:
  postgres-sandbox:
    name: vpg
  pgadmin-sandbox:
    name: vpga
